# Generated by Django 3.1.3 on 2021-01-14 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201214_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Enter phone number with our without +()', max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\\s\\./0-9]*$', 'Enter a valid phone number.', 'invalid')], verbose_name='Phone Number')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('linked_In_URL', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
